In [2]:
import numpy as np

In [3]:
def gram_schmidt(A):
    
    A = np.array(A, dtype=float)
    m, n = A.shape
    
    U = np.zeros((m, n), dtype=float)
    Q = np.zeros((m, n), dtype=float)
    
    for k in range(n):
        v_k = A[:, k]
        u_k = v_k.copy()
        
        for j in range(k):
            u_j = U[:, j]
            # projection of v_k onto u_j
            proj_coeff = np.dot(v_k, u_j) / np.dot(u_j, u_j)
            u_k -= proj_coeff * u_j
            
        U[:, k] = u_k
        
        Q[:, k] = u_k / np.linalg.norm(u_k)
        
    return Q



        ## verifying
if __name__ == "__main__":
    #  take  matrix A with linearly independent columns
    A_test = np.array([
        [1, 1, 0],
        [1, 0, 1],
        [0, 1, 1]
    ])
    
    # get orthonormal matrix Q
    Q_test = gram_schmidt(A_test)
    
    print("Matrix A:")
    print(A_test)
    print("Matrix Q:")
    print(np.round(Q_test, 4))
    
    # Verifying  Q^T * Q = I
    n_cols = A_test.shape[1]
    identity_approx = Q_test.T @ Q_test
    
    print(np.round(identity_approx, 4))
    
    # another check using np.allclose
    
    is_orthonormal = np.allclose(identity_approx, np.eye(n_cols))
    
    print(f"Verification Passed (Q^T @ Q == I): {is_orthonormal}")

Matrix A:
[[1 1 0]
 [1 0 1]
 [0 1 1]]
Matrix Q:
[[ 0.7071  0.4082 -0.5774]
 [ 0.7071 -0.4082  0.5774]
 [ 0.      0.8165  0.5774]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Verification Passed (Q^T @ Q == I): True
